version: "3.8"
services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.buildcaddy
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 2019:2019
      - 81:81
    networks:
      - caddy-bridge-network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./site:/srv

  webserver:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    env_file: ./.env
    networks:
      - caddy-bridge-network
    depends_on:
      - caddy
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./frontend/build:/frontend/build
      - ./server:/server
      - /server/node_modules

volumes:
  caddy_data:
  caddy_config:


networks:
  caddy-bridge-network:
    driver: bridge
    external: true
